name: Build Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: make
      - run: make usage
      - run: make debug
      - run: make release
      - run: sudo make install
      - run: make examples
      - run: sudo make uninstall
      - run: make clean
